# Generated by tools/brew_formula.py — do not edit by hand.
#
#   brew tap g-battaglia/ai-epub-translator https://github.com/g-battaglia/ai-epub-translator
#   brew install g-battaglia/ai-epub-translator/ai-epub-translator
class AiEpubTranslator < Formula
  include Language::Python::Virtualenv

  desc "Translate EPUB ebooks with a local LLM, offline"
  homepage "https://github.com/g-battaglia/ai-epub-translator"
  url "https://files.pythonhosted.org/packages/source/a/ai-epub-translator/ai_epub_translator-1.0.1.tar.gz"
  sha256 "f2be498b14dc791e245ea9fe7b7990fdea6aa4a5ed8808b14b00e56ce84a6cd6"
  license "MIT"
  head "https://github.com/g-battaglia/ai-epub-translator.git", branch: "main"

  depends_on "libxml2"
  depends_on "libxslt"
  depends_on "python@3.13"

  resource "lxml" do
    url "https://files.pythonhosted.org/packages/ad/a9/970b8fa0ecc4fbf1dfaed0d89bbc1fc1421b25ec26a2038c91e872dc6c8e/lxml-6.1.2.tar.gz"
    sha256 "1055241852f2b02068af4a625a5d32c087db193c12251928af2562ecd2239f18"
  end

  def install
    # lxml has no wheel here: it compiles against the keg-only libxml2/libxslt.
    ENV.prepend_path "PATH", Formula["libxml2"].opt_bin
    ENV.prepend_path "PATH", Formula["libxslt"].opt_bin
    ENV.prepend_path "PKG_CONFIG_PATH", Formula["libxml2"].opt_lib/"pkgconfig"
    ENV.prepend_path "PKG_CONFIG_PATH", Formula["libxslt"].opt_lib/"pkgconfig"

    virtualenv_install_with_resources
  end

  def caveats
    <<~EOS
      The translation runs on your own machine: point the tool at an
      OpenAI-compatible server (Ollama, LM Studio, llama.cpp, vLLM, omlx), then

        ai-epub-translator config init   # ~/.config/ai-epub-translator/config.toml
        ai-epub-translator doctor        # is the server up? which models does it offer?
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ai-epub-translator --version")

    # An empty library lists nothing and exits 0; `config init` writes the
    # commented template. Neither touches the network.
    ENV["AI_EPUB_TRANSLATOR_BOOKS"] = (testpath/"books").to_s
    ENV["AI_EPUB_TRANSLATOR_CONFIG"] = (testpath/"config.toml").to_s
    system bin/"ai-epub-translator", "list"
    system bin/"ai-epub-translator", "config", "init"
    assert_path_exists testpath/"config.toml"
  end
end
