"""Write ``Formula/ai-epub-translator.rb`` from the published artefacts.

Homebrew needs two things this repository cannot invent: the URL of the sdist on
PyPI and its SHA-256 — which exist only once the release is published. The formula
is therefore generated, never hand-edited, and its commit necessarily comes after
the tag:

    python3 tools/brew_formula.py                        # from PyPI
    python3 tools/brew_formula.py --sdist dist/*.tar.gz   # before the upload

The version always comes from ``pyproject.toml``; ``lxml`` (the single runtime
dependency, compiled against Homebrew's libxml2/libxslt) is pinned to its latest
sdist unless ``--lxml-version`` says otherwise.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import time
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FORMULA = os.path.join(ROOT, "Formula", "ai-epub-translator.rb")
PROJECT = "ai-epub-translator"

TEMPLATE = '''\
# Generated by tools/brew_formula.py — do not edit by hand.
#
#   brew tap g-battaglia/ai-epub-translator https://github.com/g-battaglia/ai-epub-translator
#   brew install g-battaglia/ai-epub-translator/ai-epub-translator
class AiEpubTranslator < Formula
  include Language::Python::Virtualenv

  desc "Translate EPUB ebooks with a local LLM, offline"
  homepage "https://github.com/g-battaglia/ai-epub-translator"
  url "{url}"
  sha256 "{sha256}"
  license "MIT"
  head "https://github.com/g-battaglia/ai-epub-translator.git", branch: "main"

  depends_on "libxml2"
  depends_on "libxslt"
  depends_on "python@{python}"

  resource "lxml" do
    url "{lxml_url}"
    sha256 "{lxml_sha256}"
  end

  def install
    # lxml has no wheel here: it compiles against the keg-only libxml2/libxslt.
    ENV.prepend_path "PATH", Formula["libxml2"].opt_bin
    ENV.prepend_path "PATH", Formula["libxslt"].opt_bin
    ENV.prepend_path "PKG_CONFIG_PATH", Formula["libxml2"].opt_lib/"pkgconfig"
    ENV.prepend_path "PKG_CONFIG_PATH", Formula["libxslt"].opt_lib/"pkgconfig"

    virtualenv_install_with_resources
  end

  def caveats
    <<~EOS
      The translation runs on your own machine: point the tool at an
      OpenAI-compatible server (Ollama, LM Studio, llama.cpp, vLLM, omlx), then

        ai-epub-translator config init   # ~/.config/ai-epub-translator/config.toml
        ai-epub-translator doctor        # is the server up? which models does it offer?
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/ai-epub-translator --version")

    # An empty library lists nothing and exits 0; `config init` writes the
    # commented template. Neither touches the network.
    ENV["AI_EPUB_TRANSLATOR_BOOKS"] = (testpath/"books").to_s
    ENV["AI_EPUB_TRANSLATOR_CONFIG"] = (testpath/"config.toml").to_s
    system bin/"ai-epub-translator", "list"
    system bin/"ai-epub-translator", "config", "init"
    assert_path_exists testpath/"config.toml"
  end
end
'''


def _pypi(project: str) -> dict:
    with urllib.request.urlopen(f"https://pypi.org/pypi/{project}/json", timeout=30) as r:
        return json.load(r)


def _sdist(project: str, version: str = None, wait: int = 0) -> tuple:
    """(url, sha256, version) of a project's sdist on PyPI — the latest unless pinned.

    ``wait`` seconds of polling covers the minute in which an upload is not yet
    visible on the JSON API (the release workflow runs right after publishing).
    """
    deadline = time.time() + wait
    while True:
        data = _pypi(project)
        release = version or data["info"]["version"]
        for f in data.get("releases", {}).get(release, []):
            if f["packagetype"] == "sdist":
                return f["url"], f["digests"]["sha256"], release
        if time.time() >= deadline:
            raise SystemExit(f"{project} {release} has no sdist on PyPI "
                             f"(use --sdist to generate the formula from a local build)")
        time.sleep(15)


def source_url(version: str) -> str:
    """PyPI's stable /source/ URL — known before the upload, so the formula can be
    generated from a local build and stay byte-identical after the release."""
    return (f"https://files.pythonhosted.org/packages/source/"
            f"{PROJECT[0]}/{PROJECT}/ai_epub_translator-{version}.tar.gz")


def _local_sha256(path: str, version: str) -> str:
    name = os.path.basename(path)
    if version not in name:
        raise SystemExit(f"{name} is not version {version}")
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def project_version() -> str:
    with open(os.path.join(ROOT, "pyproject.toml"), encoding="utf-8") as f:
        m = re.search(r'^version = "([^"]+)"', f.read(), re.M)
    if not m:
        raise SystemExit("no version in pyproject.toml")
    return m.group(1)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--sdist", help="local sdist to hash, instead of the one on PyPI")
    ap.add_argument("--wait", type=int, default=0, metavar="SECONDS",
                    help="poll PyPI until the release shows up (after publishing)")
    ap.add_argument("--lxml-version", help="pin lxml (default: its latest sdist)")
    ap.add_argument("--python", default="3.13", help="the python@X.Y formula to build against")
    ap.add_argument("-o", "--output", default=FORMULA)
    args = ap.parse_args(argv)

    version = project_version()
    url = source_url(version)
    if args.sdist:
        sha256 = _local_sha256(args.sdist, version)
    else:
        _, sha256, _ = _sdist(PROJECT, version, wait=args.wait)
    lxml_url, lxml_sha256, lxml_version = _sdist("lxml", args.lxml_version)

    text = TEMPLATE.format(url=url, sha256=sha256, python=args.python,
                           lxml_url=lxml_url, lxml_sha256=lxml_sha256)
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"{os.path.relpath(args.output, ROOT)}: {PROJECT} {version} · lxml {lxml_version}")
    print(f"  {url}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
